### ISSUE TITLE
Does this template work anymore?

### ISSUE THREAD

**Issue by dmhendricks** [htmlburger/carbon-field-template#1]
I tried to create a custom field type using this template. I followed the instructions (I think? They seem rather easy.)

When I tried to create my new field:
`Field::make('code', 'crb_code_field_text')`

I get the error:
> Warning: include_once(/path/to/my/site/wp-content/plugins/carbon-fields/core/Field/Code_Field.php): failed to open stream: No such file or directory

It appears that it is looking for the class file for my new field in the carbon-fields core folder rather than in my own plugin's Code_Field.php. Do you know how I can fix this?

It's kind of a big show stopper. :(

**Comment by m1r0** [comment]
Hi @dmhendricks and thanks for the report.

Just checked the template and fixed a problem with the `admin_enqueue_scripts` method definition (https://github.com/htmlburger/carbon-field-template/commit/1b138fbcb881296310aef50f78a453245c9eda9b), but can't reproduce the problem that you are getting.

Here is the test field that I made in order to check the functionality: [test-field.zip](https://github.com/htmlburger/carbon-field-template/files/686973/test-field.zip)

Is it possible to share some more info?

**Comment by emilsgulbis** [comment]
@m1r0 Looks like there still is problem with **admin_enqueue_scripts** if I place test-field on my theme.
`$dir = plugin_dir_url( __FILE__ )` isn't the thing for this case

**Comment by m1r0** [comment]
@emilsgulbis The intention for this template is to be used as a plugin and is just a boilerplate, if you need to use it somewhere else - just make the necessary changes to the code to fit your needs.
